WebBanGiayAdidas/Models/ProductCategory.cs
using System;
using System.Collections.Generic;

namespace WebBanGiayAdidas.Models;

public partial class ProductCategory
{
    public int Id { get; set; }

    public string Title { get; set; } = null!;

    public string Alias { get; set; } = null!;

    public string? Description { get; set; }

    public string? Icon { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifierDate { get; set; }

    public string? ModifierBy { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}

WebBanGiayAdidas/Areas/Admin/Controllers/ProductCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using WebBanGiayAdidas.Models;

namespace WebBanGiayAdidas.Areas.Admin.Controllers
{
	[Authorize(Roles = "Admin")]
	[Area("Admin")]
    public class ProductCategoriesController : Controller
    {
        private readonly WebBanGiayAdidasContext _context;

        public ProductCategoriesController(WebBanGiayAdidasContext context)
        {
            _context = context;
        }

        // GET: Admin/ProductCategories
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.ProductCategories.ToListAsync());
        //}
        public async Task<IActionResult> Index(string keyword, int? page)
        {
            var pageSize = 5;
            var pageIndex = page ?? 1;

            var pclist = _context.ProductCategories.AsQueryable();

            if (!string.IsNullOrEmpty(keyword))
            {
                pclist = pclist.Where(n => n.Title.Contains(keyword));
            }

            var totalItems = await pclist.CountAsync();
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var items = await pclist
                .OrderByDescending(n => n.CreatedDate)
                .Skip((pageIndex - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            ViewBag.CurrentPage = pageIndex;
            ViewBag.TotalPages = totalPages;
            ViewBag.Keyword = keyword;

            return View(items);
        }

        // GET: Admin/ProductCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategory = await _context.ProductCategories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productCategory == null)
            {
                return NotFound();
            }

            return View(productCategory);
        }

        // GET: Admin/ProductCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/ProductCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Icon,CreatedDate,CreatedBy,ModifierDate,ModifierBy,Alias")] ProductCategory productCategory, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", "productcategories", imageFile.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }
                    productCategory.Icon = "/uploads/productcategories/" + imageFile.FileName;
                }
                // Nếu Alias bị bỏ trống thì tạo từ Title
                if (string.IsNullOrEmpty(productCategory.Alias))
                {
                    productCategory.Alias = productCategory.Title;
                }

                // Chuẩn hoá Alias
                productCategory.Alias = WebBanGiayAdidas.Models.Common.Filter.FilterChar(productCategory.Alias);

                _context.Add(productCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productCategory);
        }

        // GET: Admin/ProductCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategory = await _context.ProductCategories.FindAsync(id);
            if (productCategory == null)
            {
                return NotFound();
            }
            return View(productCategory);
        }

        // POST: Admin/ProductCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Icon,CreatedDate,CreatedBy,ModifierDate,ModifierBy,Alias")] ProductCategory productCategory, IFormFile? imageFile)
        {
            if (id != productCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (imageFile != null && imageFile.Length > 0)
                    {
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", "productcategories", imageFile.FileName);
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await imageFile.CopyToAsync(stream);
                        }
                        productCategory.Icon = "/uploads/productcategories/" + imageFile.FileName;
                    }
                    productCategory.Alias = WebBanGiayAdidas.Models.Common.Filter.FilterChar(productCategory.Alias);
                    _context.Update(productCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductCategoryExists(productCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productCategory);
        }

        //// GET: Admin/ProductCategories/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var productCategory = await _context.ProductCategories
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (productCategory == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(productCategory);
        //}

        //// POST: Admin/ProductCategories/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var productCategory = await _context.ProductCategories.FindAsync(id);
        //    if (productCategory != null)
        //    {
        //        _context.ProductCategories.Remove(productCategory);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        // POST: Admin/ProductCategories/Delete
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var productCategory = await _context.ProductCategories.FindAsync(id);
            if (productCategory == null)
            {
                return Json(new { success = false, message = "Tin tức không tồn tại." });
            }

            try
            {
                _context.ProductCategories.Remove(productCategory);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Xóa thành công." });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Lỗi khi xóa: " + ex.Message });
            }
        }

        private bool ProductCategoryExists(int id)
        {
            return _context.ProductCategories.Any(e => e.Id == id);
        }
    }
}

WebBanGiayAdidas/Areas/Admin/Views/ProductCategories/Create.cshtml
@model WebBanGiayAdidas.Models.ProductCategory

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Admin.cshtml";
}
@section naviheader {
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="ProductCategories" asp-action="Index" class="nav-link">Danh mục sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="ProductCategories" asp-action="Create" class="nav-link">Thêm mới</a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới danh mục sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    @*                     <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Categories" asp-action="Index">Danh mục</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li> *@
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin danh mục sản phẩm</h3>
        </div>
        <div class="card-body">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label">Tên danh mục</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Alias" class="control-label">Alias</label>
                    <input asp-for="Alias" class="form-control" />
                    <span asp-validation-for="Alias" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Icon" class="control-label">Icon</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input asp-for="Icon" type="file" class="custom-file-input" id="imageUpload" name="imageFile" accept="image/*">
                            <label class="custom-file-label" for="imageUpload">Chọn ảnh</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Tải lên</span>
                        </div>
                    </div>
                    <span asp-validation-for="Icon" class="text-danger"></span>
                </div>
                <img id="previewImage" src="#" alt="Ảnh xem trước" style="max-width: 200px; display: none; margin-top: 10px;" />
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Mô tả</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedDate" class="control-label"></label>
                    <input asp-for="CreatedDate" class="form-control" />
                    <span asp-validation-for="CreatedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedBy" class="control-label"></label>
                    <input asp-for="CreatedBy" class="form-control" />
                    <span asp-validation-for="CreatedBy" class="text-danger"></span>
                </div>
                @* <div class="form-group">
                    <label asp-for="ModifierDate" class="control-label"></label>
                    <input asp-for="ModifierDate" class="form-control" />
                    <span asp-validation-for="ModifierDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ModifierBy" class="control-label"></label>
                    <input asp-for="ModifierBy" class="form-control" />
                    <span asp-validation-for="ModifierBy" class="text-danger"></span>
                </div> *@
                <a asp-action="Index" class="btn btn-danger">Quay lại</a>
                <button type="submit" value="Create" class="btn btn-primary">Thêm mới</button>
            </form>
        </div>
        <!-- /.card-body -->
        @* <div class="card-footer">
        Footer
        </div> *@
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        document.getElementById('imageUpload').addEventListener('change', function (event) {
            const file = event.target.files[0];
            if (file) {
                // Hiển thị tên tệp đã chọn
                this.nextElementSibling.innerText = file.name;

                // Xem trước ảnh
                const reader = new FileReader();
                reader.onload = function (e) {
                    const preview = document.getElementById('previewImage');
                    preview.src = e.target.result;
                    preview.style.display = 'block';
                };
                reader.readAsDataURL(file);
            }
        });
    </script>
}

WebBanGiayAdidas/Areas/Admin/Views/ProductCategories/Delete.cshtml
@model WebBanGiayAdidas.Models.ProductCategory

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Admin.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductCategory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Icon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Icon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifierDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifierDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifierBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifierBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebBanGiayAdidas/Areas/Admin/Views/ProductCategories/Details.cshtml
@model WebBanGiayAdidas.Models.ProductCategory

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Admin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>ProductCategory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Icon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Icon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifierDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifierDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifierBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifierBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebBanGiayAdidas/Areas/Admin/Views/ProductCategories/Edit.cshtml
@model WebBanGiayAdidas.Models.ProductCategory

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Admin.cshtml";
}

@* <h1>Edit</h1>

<h4>ProductCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icon" class="control-label"></label>
                <input asp-for="Icon" class="form-control" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifierDate" class="control-label"></label>
                <input asp-for="ModifierDate" class="form-control" />
                <span asp-validation-for="ModifierDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifierBy" class="control-label"></label>
                <input asp-for="ModifierBy" class="form-control" />
                <span asp-validation-for="ModifierBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div> *@
@section naviheader {
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="ProductCategories" asp-action="Index" class="nav-link">Danh mục sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="ProductCategories" asp-action="Edit" class="nav-link">Chỉnh sửa</a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cập nhật bài viết</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    @*                     <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="News" asp-action="Index">Tin tức</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li> *@
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin bài viết</h3>
        </div>
        <div class="card-body">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label">Tên danh mục</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Alias" class="control-label">Alias</label>
                    <input asp-for="Alias" class="form-control" />
                    <span asp-validation-for="Alias" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Icon" class="control-label">Icon</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input asp-for="Icon" type="file" class="custom-file-input" id="imageUpload" name="imageFile" accept="image/*" />
                            <label class="custom-file-label" for="imageUpload">Chọn ảnh</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Tải lên</span>
                        </div>
                    </div>
                    <span asp-validation-for="Icon" class="text-danger"></span>
                </div>
                @if (!string.IsNullOrEmpty(Model.Icon))
                {
                    <img id="previewImage" src="@Model.Icon" alt="Ảnh xem trước" style="max-width: 200px; display: block; margin-top: 10px;" />
                }
                else
                {
                    <img id="previewImage" src="#" alt="Ảnh xem trước" style="max-width: 200px; display: none; margin-top: 10px;" />
                }
                <img id="previewImage" src="#" alt="Ảnh xem trước" style="max-width: 200px; display: none; margin-top: 10px;" />
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Mô tả</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                @* <div class="form-group">
                    <label asp-for="CreatedDate" class="control-label"></label>
                    <input asp-for="CreatedDate" class="form-control" />
                    <span asp-validation-for="CreatedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedBy" class="control-label"></label>
                    <input asp-for="CreatedBy" class="form-control" />
                    <span asp-validation-for="CreatedBy" class="text-danger"></span>
                </div> *@
                <div class="form-group">
                <label asp-for="ModifierDate" class="control-label"></label>
                <input asp-for="ModifierDate" class="form-control" />
                <span asp-validation-for="ModifierDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                <label asp-for="ModifierBy" class="control-label"></label>
                <input asp-for="ModifierBy" class="form-control" />
                <span asp-validation-for="ModifierBy" class="text-danger"></span>
                </div>
                <a asp-action="Index" class="btn btn-danger">Quay lại</a>
                <button type="submit" value="Edit" class="btn btn-primary">Sửa</button>
            </form>
        </div>
        <!-- /.card-body -->
        @* <div class="card-footer">
        Footer
        </div> *@
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
<script>
    document.getElementById('imageUpload').addEventListener('change', function (event) {
        const file = event.target.files[0];
        if (file) {
            // Hiển thị tên tệp đã chọn
            this.nextElementSibling.innerText = file.name;

            // Xem trước ảnh
            const reader = new FileReader();
            reader.onload = function (e) {
                const preview = document.getElementById('previewImage');
                preview.src = e.target.result;
                preview.style.display = 'block';
            };
            reader.readAsDataURL(file);
        }
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}